In [1]:
!pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
!pip install torch-cluster -f https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
!pip install torch-spline-conv -f https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
!pip install torch-geometric -f https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html

Looking in links: https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
Looking in links: https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
Looking in links: https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
Looking in links: https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html
Looking in links: https://data.pyg.org/whl/torch-2.0.1%2Bcu118.html


In [2]:
import torch
print(torch.__version__)

2.0.1


In [1]:
import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.datasets import FacebookPagePage


torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# Cora Dataset

In [4]:
# Import dataset from PyTorch Geometric
dataset = Planetoid(root=".", name="Cora")

Processing...
Done!


In [5]:
data = dataset[0]

# Print information about the dataset
print(f'Dataset: {dataset}')
print('---------------')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of nodes: {data.x.shape[0]}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

# Print information about the graph
print(f'\nGraph:')
print('------')
print(f'Edges are directed: {data.is_directed()}')
print(f'Graph has isolated nodes: {data.has_isolated_nodes()}')
print(f'Graph has loops: {data.has_self_loops()}')

Dataset: Cora()
---------------
Number of graphs: 1
Number of nodes: 2708
Number of features: 1433
Number of classes: 7

Graph:
------
Edges are directed: False
Graph has isolated nodes: False
Graph has loops: False


In [6]:
dataset.data

C:\Users\armod\anaconda3\Lib\site-packages\torch_geometric\data\in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [7]:
dataset.y

tensor([3, 4, 4,  ..., 3, 3, 3])

In [8]:
dataset.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [9]:
dataset.edge_index

tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])

In [10]:
dataset.edge_index.shape

torch.Size([2, 10556])

# Facebook Dataset

In [11]:
dataset = FacebookPagePage(root=".")

data = dataset[0]

# Print information about the dataset
print(f'Dataset: {dataset}')
print('-----------------------')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of nodes: {data.x.shape[0]}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

# Print information about the graph
print(f'\nGraph:')
print('------')
print(f'Edges are directed: {data.is_directed()}')
print(f'Graph has isolated nodes: {data.has_isolated_nodes()}')
print(f'Graph has loops: {data.has_self_loops()}')

# Create masks
data.train_mask = range(18000)
data.val_mask = range(18001, 20000)
data.test_mask = range(20001, 22470)

Dataset: FacebookPagePage()
-----------------------
Number of graphs: 1
Number of nodes: 22470
Number of features: 128
Number of classes: 4

Graph:
------
Edges are directed: False
Graph has isolated nodes: False
Graph has loops: True


Processing...
Done!


In [12]:
dataset.data

Data(x=[22470, 128], edge_index=[2, 342004], y=[22470])

In [13]:
dataset.x

tensor([[-0.2626, -0.2765, -0.2624,  ..., -0.2151, -0.3759, -0.2238],
        [-0.2626, -0.2765, -0.2624,  ..., -0.2151, -0.3641, -0.1286],
        [-0.2626, -0.2651, -0.2624,  ..., -0.2151, -0.3759, -0.2238],
        ...,
        [-0.2626, -0.2765, -0.2624,  ..., -0.1804, -0.3721, -0.2226],
        [-0.2626, -0.2765, -0.2624,  ..., -0.2151, -0.3759, -0.2181],
        [-0.2323, -0.2765, -0.2624,  ..., -0.1959, -0.3759, -0.2213]])

In [14]:
dataset.y

tensor([0, 2, 1,  ..., 2, 1, 0])

In [15]:
dataset.edge_index

tensor([[    0, 18427,     1,  ...,  5563, 22425, 22425],
        [18427,     0, 21708,  ...,  5563, 22425, 22425]])